name: Pipeline ViaCep

on:
  push:
    branches:
      - main

jobs:
  request-cep:
    runs-on: ubuntu-latest

    steps:
    # 1. Configuração do ambiente
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install axios

    # 2. Execução do Script com Axios
    - name: Run CEP request script
      run: |
        node consultaCep.js

    # 3. Validação da resposta
    - name: Validate response
      run: |
        # Aqui, o script deve validar se a resposta está no formato correto
        # Pode-se utilizar um simples check de status HTTP ou verificação de conteúdo no corpo
        curl -s -o /dev/null -w "%{http_code}" https://viacep.com.br/ws/01001000/json/
    
    # 4. Exibição dos Dados
    - name: Display CEP data
      run: |
        node exibeCep.js
