name: Testar servidor Node.js

on:
  push:
    branches:
      - main

jobs:
  build_and_run:
    runs-on: ubuntu-latest
  
    steps:
    # Passo 1: Checkout
    - name: Checkout do código
      uses: actions/checkout@v3

    # Passo 2: Configurar Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Passo 3: Instalar as dependências
    - name: Instalar as dependências
      run: npm install
    
    # Passo 4: Rodar o servidor
    - name: Rodar o servidor
      run: |
        nohup node app.js &
        echo "Servidor rodando em segundo plano..."
    
    # Passo 5: Testar se o servidor está funcionando
    - name: Testar se o servidor está funcionando
      run: |
        sleep 10 # Espera o servidor iniciar
        curl http://localhost:3000 # Verifica se o servidor responde 
